version: "3.8"
services:
  dev-env:
    build: .
    image: ubuntu:ddc
    volumes:
      - ..:/developer
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_SESSION_EXPIRES=${AWS_SESSION_EXPIRES}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - ARTIFACTORY_USERNAME=${ARTIFACTORY_USERNAME}
      - ARTIFACTORY_TOKEN=${ARTIFACTORY_TOKEN}
    stdin_open: true
    tty: true